services:
  nginx:
    image: nginx:latest
    container_name: orange-nginx
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/example.com/fullchain.pem:/etc/nginx/fullchain.pem:ro
      - /etc/letsencrypt/live/example.com/privkey.pem:/etc/nginx//privkey.pem:ro
    restart: unless-stopped